allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  cpu-features: true
  esbuild: true
  ssh2: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@thallesp/nestjs-better-auth@2.7.0'
  - '@stlmpp/nestjs-zod@1.0.1'
