/* eslint-disable */
export default async () => {
    const t = {
        ["./shared/model/response-error.model"]: await import("./shared/model/response-error.model"),
        ["./features/health/health.response"]: await import("./features/health/health.response"),
        ["./features/customer/dto/output/create-customer.response"]: await import("./features/customer/dto/output/create-customer.response"),
        ["./features/customer/dto/output/list-customer.response"]: await import("./features/customer/dto/output/list-customer.response"),
        ["./features/customer/dto/output/get-customer.response"]: await import("./features/customer/dto/output/get-customer.response"),
        ["./features/config/dto/output/publish-config.response"]: await import("./features/config/dto/output/publish-config.response"),
        ["./features/config/dto/output/list-config.response"]: await import("./features/config/dto/output/list-config.response")
    };
    return { "@nestjs/swagger": { "models": [[import("./features/customer/dto/input/list-customer.request"), { "FilterCustomerDto": {} }], [import("./features/config/dto/input/list-config.request"), { "FilterConfigDto": {} }], [import("./features/health/health.response"), { "HealthResponse": {} }], [import("./features/customer/dto/input/update-customer.request"), { "UpdateCustomerDto": {}, "UpdateCustomerRequest": {} }], [import("./features/customer/dto/input/create-customer.request"), { "CreateCustomerDto": {}, "CustomerCreateRequest": {} }], [import("./features/customer/dto/output/create-customer.response"), { "CreateCustomerResponseModel": {} }], [import("./features/customer/dto/output/get-customer.response"), { "GetCustomerResponseModel": {} }], [import("./shared/model/response-error.model"), { "ErrorDetailModel": { issue: { required: true, type: () => String }, field: { required: true, type: () => String } }, "ErrorModel": { code: { required: true, type: () => String }, message: { required: true, type: () => String }, error: { required: true, type: () => String }, details: { required: false, type: () => [t["./shared/model/response-error.model"].ErrorDetailModel] } }, "ResponseErrorModel": { error: { required: true, type: () => t["./shared/model/response-error.model"].ErrorModel }, statusCode: { required: true, type: () => Number } } }], [import("./features/customer/dto/output/list-customer.response"), { "ListCustomerResponseModel": {} }], [import("./features/config/dto/input/publish-config.request"), { "PublishConfigDto": {}, "PublishConfigRequest": {} }], [import("./features/config/dto/output/publish-config.response"), { "PublishConfigResponseModel": {} }], [import("./features/config/dto/output/list-config.response"), { "ListConfigResponseModel": {} }]], "controllers": [[import("./features/health/health.controller"), { "HealthController": { "health": { type: t["./features/health/health.response"].HealthResponse } } }], [import("./features/customer/customer.controller"), { "CustomerController": { "create": { type: t["./features/customer/dto/output/create-customer.response"].CreateCustomerResponseModel }, "update": {}, "listPaginated": { type: t["./features/customer/dto/output/list-customer.response"].ListCustomerResponseModel }, "getById": { type: t["./features/customer/dto/output/get-customer.response"].GetCustomerResponseModel } } }], [import("./features/config/config.controller"), { "ConfigController": { "publish": { type: t["./features/config/dto/output/publish-config.response"].PublishConfigResponseModel }, "listPaginated": { type: t["./features/config/dto/output/list-config.response"].ListConfigResponseModel } } }]] } };
};